version: '3.7'
services:
    githubrunnerwindows:
      container_name: githubrunnerwindows
      isolation: "hyperv"
      build: 
        context: ./
        dockerfile: windows1909.txt
        args:
          GITHUB_REPO_URL:   ${GITHUB_REPO_URL}
          GITHUB_REPO_TOKEN: ${GITHUB_REPO_TOKEN_WINDOWS}
      deploy:
        resources:
          limits:
            memory: 2GB
    githubrunnerlinux:
      container_name: githubrunnerlinux
      isolation: "hyperv"
      build: 
        context: ./
        dockerfile: ubuntu.txt
        args:  
          GITHUB_REPO_URL:   ${GITHUB_REPO_URL}
          GITHUB_REPO_TOKEN: ${GITHUB_REPO_TOKEN_LINUX}
      deploy:
        resources:
          limits:
            memory: 2GB
