version: '2.1'
services:
    githubrunnerwindows:
      container_name: githubrunnerwindows
      isolation: "hyperv"
      build: 
        context: ./
        dockerfile: windows1909.txt
        args:
          GITHUB_REPO_URL:   ${GITHUB_REPO_URL}
          GITHUB_REPO_TOKEN: ${GITHUB_REPO_TOKEN_WINDOWS}
      mem_limit: 8GB
    githubrunnerlinux:
      container_name: githubrunnerlinux
      isolation: "hyperv"
      build: 
        context: ./
        dockerfile: ubuntu.txt
        args:  
          GITHUB_REPO_URL:   ${GITHUB_REPO_URL}
          GITHUB_REPO_TOKEN: ${GITHUB_REPO_TOKEN_LINUX}
      mem_limit: 8GB
